apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    database: sentiment
    user: admin
    secureJsonData:
      password: YOURPASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
